### ISSUE TITLE
Hi, how can i get the coordinates of  individual character regions in natural images ?

### ISSUE THREAD

**Issue by yugengde** [clovaai/CRAFT-pytorch#10]

**Comment by zhenx** [comment]
Based on my understanding, change the following line of the code in getDetBoxes_core() in craft_utils.py, hope it helps. 
--before
22: text_score_comb = np.clip(text_score + link_score, 0, 1)
--after
22: text_score_comb = np.clip(text_score, 0, 1)

**Comment by yugengde** [comment]
thank you zhenx, i have tried your code, but i still could not got the individual character regions , recogning some characters as one character  some time.

**Comment by yugengde** [comment]
> Based on my understanding, change the following line of the code in getDetBoxes_core() in craft_utils.py, hope it helps.
> --before
> 22: text_score_comb = np.clip(text_score + link_score, 0, 1)
> --after
> 22: text_score_comb = np.clip(text_score, 0, 1)

thank you zhenx, i have tried your code, but i still could not got the individual character regions , recogning some characters as one character some time.

**Comment by YoungminBaek** [comment]
The final result does not have the coordinates of individual characters. We perform the connected-component labeling the merged text map made from the region map and the affinity map. This repo contains only post-processing of the final result.

If you are asking about the character coordinates for weakly-supervised training, please refer to the paper.
The procedure for obtaining the coordinate of the individual character is shown in the following figure.
![image](https://user-images.githubusercontent.com/13248735/60766929-321c8780-a0eb-11e9-8352-8fc5da8c311a.png)

**Comment by yugengde** [comment]
> The final result does not have the coordinates of individual characters. We perform the connected-component labeling the merged text map made from the region map and the affinity map. This repo contains only post-processing of the final result.
> 
> If you are asking about the character coordinates for weakly-supervised training, please refer to the paper.
> The procedure for obtaining the coordinate of the individual character is shown in the following figure.
> ![image](https://user-images.githubusercontent.com/13248735/60766929-321c8780-a0eb-11e9-8352-8fc5da8c311a.png)

many thanks!

**Comment by YanShuang17** [comment]
@YoungminBaek Hi, thanks for your excellent work. I have a question about Figure 4 of CRAFT paper:
There are three lines of picture, in the first line, the interim model predict 3 word patches, and the predicted char numbers are 6/5/5. But its corresponding region heatmap in the 2nd line shows that the char numbers are not 6/5/5, but 5/6/6?
Is there something wrong here? waiting for your expanantion!!! thanks

**Comment by jussyr** [comment]
@YanShuang17 My understanding is that the numbers in the top right [ (6/6), (5/7), (5/6) ] are used to weight the confidence map over each word box as stated in the paragraph proceeding that image:

"In order to reflect the reliability of the interim model’s prediction, the value of the confidence map over each word box is computed proportional to the number of the detected characters divided by the number of the ground truth characters, which is used for the learning weight during training."

They estimated region/character score, i.e., the Gaussian heat map, is used to segment the image into separate characters.  In some cases the gap between is too small and they end up grouped into one.  This is the first number in each case (i.e. the 6, 5, and 5).  However, the dataset lists the number of characters in each word box, i.e., the number of ground truth characters (the 2nd number in each case, i.e. 6, 7, and 6).
