### ISSUE TITLE
When will you release your training code?

### ISSUE THREAD

**Issue by lillyPJ** [clovaai/CRAFT-pytorch#17]

**Comment by AyushP123** [comment]
To add to this, if you are not releasing the code and the best trained model, is it available commercially??

**Comment by brooklyn1900** [comment]
That's what I want to ask too!

**Comment by nunenuh** [comment]
Yes, I want to hear the answer to this question

**Comment by brooklyn1900** [comment]
@lillyPJ Did you get the training code?

**Comment by YoungminBaek** [comment]
@AyushP123 Yes, you can use this code and the pre-trained model commercially.

As explained in https://github.com/clovaai/CRAFT-pytorch/issues/2, due to the regulation of the company, the training code will not be disclosed.
I am really sorry to have kept you you waiting so long.
But, if you have any questions about training details, I will be happy to answer them.

**Comment by kishore0905** [comment]
> @AyushP123 No, this code is non-commercial purposes only. For commercial purposes, please contact us in advance.

is that for the model provided in this repo too?
