### ISSUE TITLE
Problems detecting single characters or numbers

### ISSUE THREAD

**Issue by Averu-zz** [clovaai/CRAFT-pytorch#26]
Hello,

I can't get bboxes of single character words. The characters are detected, but because they don't have link they don't get bounding boxes. Any way to specify that if there is only one character link threshold dont matter?

**Comment by Averu-zz** [comment]
Got it working by adjusting size variable in getDetBoxes_core() function in craft_utils.py file and lowering the text_treshold. However this also increased false positives.

**Comment by YoungminBaek** [comment]
As you pointed out, many text methods including CRAFT have difficulties with detecting a single character. We think the reason is that a single character looks like the background clutter to the model and cannot provide sufficient clues of those are texts. 

To answer your question, there is only one character link threshold does not matter. Only text_threshold and low_text are important for detection them.


At this point, there is no other way than lowering text_threshold to improve this problem as you already tried.
