### ISSUE TITLE
[Question] Selection of feature extraction network

### ISSUE THREAD

**Issue by thomasryck** [clovaai/CRAFT-pytorch#34]
I read the paper and there is no explanation of why did you choose VGG16.

Did you try other feature extraction networks as ResNet ?

If so why did you chose VGG16 ?

**Comment by cong235** [comment]
@thomasryck They chosen VGG16, i think because the feature of text or non-text just simple so just need 1 simple backbone.

**Comment by YoungminBaek** [comment]
@thomasryck 
There is no particular reason for choosing VGG16 as backbone.
As @cong235 said, we thought that VGG-16 was enough for text detection since it doesn't require as many complicated features as object detection requires.

Apart from it, we tested CRAFT with ResNet and PVANet as well, and the perforamnce difference was not significant.
