### ISSUE TITLE
Evaluation Script for ICDAR 2013, 2015

### ISSUE THREAD

**Issue by mayank-git-hub** [clovaai/CRAFT-pytorch#38]
I have been trying to evaluate your model on ICDAR 2013 and ICDAR 2015, and the F-score I get are 88.74 and 70.46 respectively, which is a far cry from what is mentioned in the paper. Could you provide the evaluation script and also clarify the dataset(s) on which the pre-trained model provided by you was trained on?

Thank You.

**Comment by deepseek** [comment]
@YoungminBaek

**Comment by YoungminBaek** [comment]
@mayank-git-hub 
Firstly, the model for IC15 is different.
Since the Chinese characters are considered as background in IC15, I trained the model for IC15 separately. I'll upload the IC15 model soon.

Secondly, the code for the post-processing has been slightly modified during the code cleaning. So, the performance gap could be observed.

Lastly, the performance of CRAFT (and maybe all other text detectors) is pretty much affected by the thresholds. We think that this is mainly due to the granularity issue, so we are trying to propose the fair evaluation method for text detectors as well. (Please check the repo https://github.com/clovaai/TedEval)

In the experiments for the paper, the thresholds were varied for each dataset due to the inconsistency of the annotation policy. For IC13, we set the link_threshold as 0.2.

If you have more questions about reproducibility, please feel free to ask me.

**Comment by mayank-git-hub** [comment]
Thank You! Sure will.
