### ISSUE TITLE
Postprocossing understanding

### ISSUE THREAD

**Issue by Godricly** [clovaai/CRAFT-pytorch#5]
When reading PostProcessing code, I was confused with these 2 parts. Your explanation is appreciated.
1. the bounding box padding intuition
```python
        niter = int(math.sqrt(size * min(w, h) / (w * h)) * 2)
        # size / (w * h) is the boundbox coverage ratio
        # 2 * min(w, h) is the area of padding alone longer edge.
```

2. the diamond-shape align
 It this a hotfix for presents of single char, typically Asian chars?

**Comment by YoungminBaek** [comment]
Sorry for the late reply. 

**1. the bounding box padding intuition**
-> The size of the detected character region is affected by the parameter named `low_text`. If this parameter is low, the character region is grouped together even though the affinity is not connected. To prevent this, we set a relatively high threshold for low_text, and then dilate the region.

**2. the diamond-shape align**
Yes, this is a hotfix to represent the single char because the single char region is generally an ellipse that makes the final result diamond-shaped box.

**Comment by HERIUN** [comment]
why just using angle of rotation in rectangle?. or just using ```cv2.boundingRect(contours)```
