### ISSUE TITLE
DataParallel isn't working

### ISSUE THREAD

**Issue by shekargoud26** [clovaai/CRAFT-pytorch#69]
I'm running this on a p2.8xlarge instance but its running only on the first GPU. It isn't using all the GPUs. How can i use all the GPUs for inference?

**Comment by YoungminBaek** [comment]
@shekargoud26 This code does not support multi-GPU inference. The DataParallel in the [code](https://github.com/clovaai/CRAFT-pytorch/blob/master/test.py#L134) is just to load the pre-trained model that trained using multi-GPUs. Sorry for making a confusion.

FYI, the batch processing for inference is a little tricky because the post-processing does not support multi-processing.
