### ISSUE TITLE
Increasing accuracy for single characters

### ISSUE THREAD

**Issue by sukumar-v** [clovaai/CRAFT-pytorch#79]
Is there any way to increase the accuracy when it comes to detecting single isolated characters? CRAFT works well with entire words but seems to miss out on characters. Will additional training on characters help?

**Comment by khoaipx** [comment]
Yes, I run CRAFT on my data. Almost single character words is missed out, such as: "I" and "a". I hope the authors improve performance those cases and release new model.

**Comment by YoungminBaek** [comment]
I am aware of this issue. The problem is the released models were trained only on the public datasets which have have very few samples of single character. As @sukumar-varma mentioned, the training with additional data solved the problem. [Demo site](https://demo.ocr.clova.ai/) However, the demo-site model was trained on the private datasets, so the release of the model is prohibited. Please excuse me for this, @khoaipx.
